name: CI Workflow

on:
  push:
    branches:
      - main   # Trigger the workflow when pushing to the `main` branch
  pull_request:
    branches:
      - main   # Trigger the workflow when opening a pull request to `main`

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies that the workflow should run on the latest Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code in the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Sets up Node.js environment
        with:
          node-version: '16'  # You can specify your required Node.js version here

      - name: Install dependencies
        run: npm install  # Install dependencies based on your `package.json`

      - name: Run tests
        run: npm test  # Run tests (you can replace this with your test command)

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update changes after workflow run" || echo "No changes to commit"
          git push origin main  # Push changes back to the `main` branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate the push
